### ISSUE TITLE
ETIMOUT on running test

### ISSUE THREAD

**Issue by foux** [LambdaTest/node-tunnel#2]
Hi,

Since today, we've got systematic timeouts as soon as the tunnel is launched. Nothing has changed on our code nor on our infrastructure. And we don't see the tunnel being created on LT

Here is the log : 
```
$ cucumber-js --require-module @babel/register --fail-fast --world-parameters='{"browser": "chrome"}'
68 Verifying credentials
69 Auth succeeded
70 Downloading latest binary
71 Extracting binary
72 Starting tunnel
73 Tunnel successfully initiated. You can start testing now
74 ..(node:460) UnhandledPromiseRejectionWarning: WebDriverError: {"message":"connect ETIMEDOUT"}
75     at Object.checkLegacyResponse (/builds/famihero-web/famihero-web/node_modules/selenium-webdriver/lib/error.js:585:15)
76     at parseHttpResponse (/builds/famihero-web/famihero-web/node_modules/selenium-webdriver/lib/http.js:554:13)
77     at Executor.execute (/builds/famihero-web/famihero-web/node_modules/selenium-webdriver/lib/http.js:489:26)
78     at runMicrotasks (<anonymous>)
79     at processTicksAndRejections (internal/process/task_queues.js:93:5)
80 (node:460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
81 (node:460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
82 (node:460) UnhandledPromiseRejectionWarning: WebDriverError: {"message":"connect ETIMEDOUT"}
83     at Object.checkLegacyResponse (/builds/famihero-web/famihero-web/node_modules/selenium-webdriver/lib/error.js:585:15)
84     at parseHttpResponse (/builds/famihero-web/famihero-web/node_modules/selenium-webdriver/lib/http.js:554:13)
85     at Executor.execute (/builds/famihero-web/famihero-web/node_modules/selenium-webdriver/lib/http.js:489:26)
86     at runMicrotasks (<anonymous>)
87     at processTicksAndRejections (internal/process/task_queues.js:93:5)
88 (node:460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by 4DvAnCeBoY** [comment]
Hi @foux, Thanks for highlighting the issue.

We have checked the issue and this has been resolved. Please connect us if it is still happening.

**Comment by Shivanshu-lambdatest** [comment]
Hi @foux I hope the issue is resolved. Please connect if it is still happening.

**Comment by dubesar** [comment]
Closing the ticket due to inactivity.
