### ISSUE TITLE
Cannot establish tunnel connection - Mac M1

### ISSUE THREAD

**Issue by Joozty** [LambdaTest/node-tunnel#9]
Hello there, when I try the script provided in your README.md it instantly fails. I guess it has something to do with that fact that I am running on Mac with a new M1 chip. Looks like you don't provide binaries for this architecture.

Node: 16.0.0
OS: MacOS Big Sur 11.4
@lambdatest/node-tunnel: 3.0.1

Output:

```
joozty@Jozefs-MacBook-Pro node-tunnel % node test.js                                        

It's seems you have older version of @lambdatest/node-tunnel.For better experience , please update using: 
npm update @lambdatest/node-tunnel
Verifying credentials

It's seems you have older version of @lambdatest/node-tunnel.For better experience , please update using: 
npm update @lambdatest/node-tunnel
Verifying credentials

It's seems you have older version of @lambdatest/node-tunnel.For better experience , please update using: 
npm update @lambdatest/node-tunnel
Verifying credentials
Auth succeeded
Checking for updates
Binary is deprecated
Downloading latest binary
Auth succeeded
Downloading latest binary
Auth succeeded
Downloading latest binary
Extracting binary
Retrying Download. Retries left 5
Downloading latest binary
Extracting binary
Extracting binary
Extracting binary
Starting tunnel
node:internal/child_process:415
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at Object.spawn (node:child_process:609:9)
    at /Users/joozty/Documents/sandboxes/node-tunnel/node_modules/@lambdatest/node-tunnel/lib/tunnel.js:314:32
    at /Users/joozty/Documents/sandboxes/node-tunnel/node_modules/@lambdatest/node-tunnel/lib/tunnel.js:730:18
    at /Users/joozty/Documents/sandboxes/node-tunnel/node_modules/@lambdatest/node-tunnel/lib/tunnel.js:767:14
    at Object.onceWrapper (node:events:471:28)
    at Server.emit (node:events:365:28)
    at emitCloseNT (node:net:1648:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

```

**Comment by Joozty** [comment]
Any update guys? 🙂  It's kind of annoying as I basically cannot use your service.

**Comment by Shivanshu-lambdatest** [comment]
Hi @Joozty , apologies for the late response. Thanks for highlighting the issue. We will look into it and fix it in up-coming versions.

**Comment by dubesar** [comment]
We have released a new version for this. Please check out and let us know. Closing this ticket, feel free to open in case of any problems.
